development:
 adapter: postgresql
 encoding: unicode
 database: solar_world_development
 pool: 5
 username:
 password:


production:
 adapter: postgresql
 encoding: unicode
 database: solar_world_development
 pool: 5
 username:
 password: